"""build_main.py - concatenate src modules into the single deliverable MAIN.py (run: python build_main.py)."""
import ast
from pathlib import Path

MODULES = ["config", "data", "gru", "text", "kalman", "ranker", "risk", "optimizer", "metrics", "report", "pipeline"]


def _strip_local_imports(text):
    """Drop `from src.x import ...` lines, including parenthesised multi-line blocks and backslash continuations."""
    out, skip = [], False
    for line in text.splitlines():
        if skip:
            skip = not (")" in line or not line.rstrip().endswith("\\"))
            continue
        if line.startswith("from src."):
            skip = ("(" in line and ")" not in line) or line.rstrip().endswith("\\")
            continue
        out.append(line)
    return "\n".join(out)


def _duplicate_names(sources):
    """Top-level def/class/assignment names defined in more than one module."""
    seen, dups = {}, []
    for mod, text in sources.items():
        for node in ast.parse(text).body:
            names = ([node.name] if isinstance(node, (ast.FunctionDef, ast.ClassDef)) else
                     [t.id for t in getattr(node, "targets", []) if isinstance(t, ast.Name)] +
                     ([node.target.id] if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) else []))
            for n in names:
                if n in seen and seen[n] != mod:
                    dups.append((n, seen[n], mod))
                seen.setdefault(n, mod)
    return dups


def build_main():
    root = Path(__file__).parent
    sources = {m: (root / "src" / f"{m}.py").read_text(encoding="utf-8") for m in MODULES}
    parts = [f"# ===== src/{m}.py =====\n{_strip_local_imports(t)}\n" for m, t in sources.items()]
    code = "# MAIN.py - auto-generated by build_main.py (do not edit; edit src/*.py)\n\n" + "\n\n".join(parts)
    code += '\n\nif __name__ == "__main__":\n    main(CONFIG)\n'
    ast.parse(code)  # syntax check
    (root / "MAIN.py").write_text(code, encoding="utf-8")
    dups = _duplicate_names(sources)
    print(f"MAIN.py built ({len(code.splitlines())} lines); duplicate top-level names: {dups or 'none'}")
    return dups


if __name__ == "__main__":
    build_main()
