"""build_main.py - concatenate src modules into the single deliverable MAIN.py (run: python build_main.py)."""
import ast
from pathlib import Path

MODULES = ["config", "data", "gru", "text", "kalman", "cfi", "ranker", "risk", "optimizer", "metrics", "report", "agent", "pipeline"]


def _strip_local_imports(text):
    """Drop `from src.x import ...` lines, including parenthesised multi-line blocks and backslash continuations."""
    out, skip = [], False
    for line in text.splitlines():
        if skip:
            skip = not (")" in line or not line.rstrip().endswith("\\"))
            continue
        if line.startswith("from src."):
            skip = ("(" in line and ")" not in line) or line.rstrip().endswith("\\")
            continue
        out.append(line)
    return "\n".join(out)


def _duplicate_names(sources):
    """Top-level def/class/assignment names defined in more than one module."""
    seen, dups = {}, []
    for mod, text in sources.items():
        for node in ast.parse(text).body:
            names = ([node.name] if isinstance(node, (ast.FunctionDef, ast.ClassDef)) else
                     [t.id for t in getattr(node, "targets", []) if isinstance(t, ast.Name)] +
                     ([node.target.id] if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) else []))
            for n in names:
                if n in seen and seen[n] != mod:
                    dups.append((n, seen[n], mod))
                seen.setdefault(n, mod)
    return dups


HEADER = """# MAIN.py - AlphaStrategy, McGill-FIAM Asset Management Hackathon 2026
#
# What this file does (run: python MAIN.py, needs the competition data in ./data, we do not ship data):
#  1. Load the stock panel, 8-K filings, TB3MS and S&P 500. Build the universe each month
#     (price >= $5, market cap above 20th percentile; shorts must also be big and liquid).
#  2. Rank the 147 characteristics to [-1, 1] each month, add missing value flags.
#  3. Kalman filter betas (fit on data up to 2018), 8-K event flags, FinBERT tone (names removed),
#     GRU autoencoder embeddings of each stock's last 11 monthly changes (trained up to 2018).
#  4. Walk-forward: for test year Y train on 2015-02..(Y-3)-12, validate on (Y-2)..(Y-1),
#     feature selection on the 147 characteristics (clusters + permutation importance on validation),
#     TabPFN return-rank regressor (optional XGBoost), refit on train + validation, predict year Y. Test years 2021-2026.
#  5. Portfolio settings and the portfolio method are chosen on 2019-2020 validation only.
#     Optimizer (cvxpy, Clarabel): max score - factor risk penalty, gross 200%, net within +/-20%,
#     beta neutral ex ante, sector and size neutral, max 1.5% per name, 100-500 names.
#  6. Performance pack, holdings.csv, returns.csv, ablations, leakage tests (incl. shuffled labels).
#  7. Analyst agent (gpt-oss-20b via Ollama, optional): explains top holdings with tools, only 8-Ks filed
#     before the trade, anonymised text, quotes checked by code. It does not change the portfolio.
# Every setting is in the CONFIG dict right below. Outputs go to ./output, intermediate files to ./cache.
#
# Licence: hackathon submission = public domain / free.
# (auto-generated by build_main.py from src/*.py)

"""


def build_main():
    root = Path(__file__).parent
    sources = {m: (root / "src" / f"{m}.py").read_text(encoding="utf-8") for m in MODULES}
    parts = [f"# ===== src/{m}.py =====\n{_strip_local_imports(t)}\n" for m, t in sources.items()]
    code = HEADER + "\n\n".join(parts)
    code += '\n\nif __name__ == "__main__":\n    main(CONFIG)\n'
    ast.parse(code)  # syntax check
    (root / "MAIN.py").write_text(code, encoding="utf-8")
    dups = _duplicate_names(sources)
    print(f"MAIN.py built ({len(code.splitlines())} lines); duplicate top-level names: {dups or 'none'}")
    return dups


if __name__ == "__main__":
    build_main()
