# MAIN.py - auto-generated by build_main.py (do not edit; edit src/*.py)

# ===== src/config.py =====
"""
src/config.py - Every setting of the pipeline in one CONFIG dict (spec: global conventions).
build_main.py puts this file first, so CONFIG sits at the top of MAIN.py.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent  # repo root when run as MAIN.py
if ROOT.name == "src":
    ROOT = ROOT.parent
DATA_DIR = ROOT / "data"
CACHE_DIR = ROOT / "cache"
OUTPUT_DIR = ROOT / "output"
for _d in [CACHE_DIR, OUTPUT_DIR, OUTPUT_DIR / "figures"]:
    _d.mkdir(parents=True, exist_ok=True)

SMOKE = os.environ.get("ALPHA_SMOKE", "0") == "1"  # tiny CPU run for local testing

try:
    import torch
    _DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
except ImportError:
    _DEVICE = "cpu"

CONFIG = {
    # --- global ---
    "seed": 42,
    "device": _DEVICE,                      # GX10: cuda (GB10 Blackwell, unified memory)
    "n_jobs": 16,                           # CPU workers for the optimizer grid (GX10: 20 Grace cores)
    "smoke": SMOKE,
    "smoke_n_permnos": 1500,                # random permno subsample in smoke mode
    "data_files": {
        "chars": DATA_DIR / "chars_final_with_names.parquet",
        "8k": DATA_DIR / "8k_20150101_20260831_identified.parquet",
        "factors": DATA_DIR / "factor_char_list.csv",
        "tb3ms": DATA_DIR / "TB3MS.csv",    # columns: eom, tb3ms (annualized %)
        "sp500": DATA_DIR / "SP500.csv",    # columns: eom, sp500_ret, sp500_source
    },
    "cache_dir": CACHE_DIR,
    "output_dir": OUTPUT_DIR,

    # --- schedule (by target month) ---
    "first_train_month": "2015-02",
    "test_years": [2021, 2022, 2023, 2024, 2025, 2026],
    "last_test_month": "2026-08",           # 2026 covers January-August only
    "tune_val_start": "2019-01",            # step 10 settings fixed on 2019-2020 validation
    "tune_val_end": "2020-12",

    # --- step 2 universe (defaults; short-eligible ME pct tuned under step 10) ---
    "min_abs_prc": 5.0,
    "universe_me_q": 0.20,                  # market_equity strictly above this pct (all stocks that month)
    "short_me_q": 0.40,                     # market_equity >= this pct (all stocks that month)
    "short_dolvol_q": 0.30,                 # dolvol_126d >= this pct of the universe
    "short_zt_q": 0.50,                     # zero_trades_126d <= universe median

    # --- step 3 ---
    "missing_flag_threshold": 0.20,

    # --- step 4 GRU ---
    "gru_seq_len": 11,
    "gru_min_valid": 6,
    "gru_hidden": 64,
    "gru_wd_grid": [0.0, 1e-4, 1e-3],
    "gru_train_end_eom": "2018-11-30",
    "gru_val_eom": ("2019-01-31", "2020-12-31"),
    "gru_lr": 1e-3,
    "gru_batch": 2048,
    "gru_max_epochs": 2 if SMOKE else 100,
    "gru_patience": 5,
    "gru_clip": 1.0,

    # --- step 5 XGBoost ranker ---
    "xgb_fixed": dict(objective="rank:pairwise", learning_rate=0.03, subsample=0.7,
                      colsample_bytree=0.5, min_child_weight=200, reg_lambda=10, tree_method="hist",
                      # xgboost>=2 normalises pairwise gradients by default -> hessians so small that
                      # min_child_weight=200 blocks splits (all depths identical). Classic behaviour:
                      lambdarank_normalization=False,
                      # xgboost>=2 defaults to "topk" pairs (only the current top-ranked docs of each month).
                      # Classic pairwise over the whole cross-section, as the spec intends:
                      lambdarank_pair_method="mean"),
    "xgb_depth_grid": [3, 4, 5],
    "xgb_max_trees": 100 if SMOKE else 2000,
    "xgb_eval_every": 50,

    # --- step 6/7 8-K ---
    "items_flag": ["1.01", "1.02", "1.03", "2.01", "2.02", "2.03", "2.05", "2.06",
                   "3.01", "4.01", "4.02", "5.02", "7.01", "8.01"],
    "items_hist": ["4.02", "5.02", "2.06", "1.02", "2.05"],
    "finbert_model": "ProsusAI/finbert",
    "finbert_chunk_tokens": 512,
    "finbert_max_chunks": 8,
    "finbert_batch": 256,                   # chunks per forward pass (bf16 on GX10)
    "finbert_max_filings": 40 if SMOKE else None,

    # --- step 8 Kalman ---
    "kalman_obs": ["beta_dimson_21d", "betadown_252d", "betabab_1260d", "beta_60m"],
    "kalman_fit_end_eom": "2018-12-31",

    # --- step 9 optimizer ---
    "n_long_cand": 250,
    "n_short_cand": 250,
    "gross": 2.0,
    "net_band": 0.20,
    "beta_tol": 0.02,
    "beta_tol_step": 0.01,
    "sector_band": 0.10,
    "max_weight": 0.015,

    # --- additions after the first full run (not in spec; chosen on 2019-2020 only) ---
    "size_band": 0.05,                      # |sum size_z * w| <= band; size_z = monthly z-score of log(me_raw)
    "lambda_risk_grid": [0.0, 100.0],       # L2 penalty lam_risk * sum(w^2): specific-risk proxy
    # factor risk model (not in spec): exposures = intercept + these ranked characteristics + sector dummies;
    # factor returns from monthly cross-sectional OLS of realised returns; covariance over trailing months
    "risk_factors": ["market_equity", "be_me", "ret_12_1", "ret_1_0", "beta_60m", "ivol_capm_252d",
                     "ope_be", "at_gr1", "dolvol_126d"],
    "risk_window": 60,                      # trailing months of factor returns
    "risk_min_months": 24,
    "lambda_fac_grid": [0.0, 300.0, 1000.0, 3000.0, 10000.0],  # lam_fac * monthly factor variance of w
    "kalman_r_floor": 0.05,                 # variant "kf_rfloor": lower bound on every R_j
    "beta_shrink": 0.33,                    # variant "b60_shrunk": (1-0.33)*beta_60m + 0.33*1
    "beta_variants": ["kf", "kf_rfloor", "b60_shrunk"],
    "beta_check_t": 1.96,                   # step 10 beta check: |t| above this = clearly nonzero -> fix betas

    # --- step 10 grids (fixed once on 2019-2020, then frozen) ---
    "gru_d_grid": [8, 16, 32],
    "lambda_tc_grid": [0.0, 0.1, 0.25, 0.5],
    "lambda_beta_grid": [0.0, 10.0, 100.0, 1000.0],
    "short_me_q_grid": [0.30, 0.40, 0.50],

    # --- step 12 template Ridge baseline ---
    "ridge_alpha_grid": [1e-1, 1, 10, 100, 1000, 10000],

    # --- metrics ---
    "premium_annual": 0.04,
    "nw_lags": 3,
}


# ===== src/data.py =====
"""
src/data.py - Steps 1-3: load inputs, universe filter, per-month rank transform (spec: steps 1-3).
"""
import numpy as np
import polars as pl


def load_inputs(cfg):
    """Step 1: chars panel + target_month, 147 factor names, deduplicated 8-K filings."""
    f = cfg["data_files"]
    factors = pl.read_csv(f["factors"])["variable"].drop_nulls().to_list()
    panel = pl.read_parquet(f["chars"]).with_columns(
        pl.col("eom").cast(pl.Date),
        pl.col("eom").cast(pl.Date).dt.offset_by("1mo").dt.month_end().alias("target_month"))
    assert panel.select(["permno", "eom"]).is_duplicated().sum() == 0, "(permno, eom) not unique"
    cols = ["document_id", "permno", "filing_date", "items", "text", "text_sha256", "company_name", "ticker"]
    filings = (pl.read_parquet(f["8k"], columns=cols).drop_nulls("permno")
               .with_columns(pl.col("filing_date").cast(pl.Date))
               .sort(["filing_date", "document_id"])
               .unique(subset=["permno", "text_sha256"], keep="first", maintain_order=True))
    if cfg["smoke"]:  # seeded permno subsample
        ids = np.sort(panel["permno"].unique().to_numpy())
        keep = np.random.default_rng(cfg["seed"]).choice(ids, min(cfg["smoke_n_permnos"], len(ids)), replace=False)
        panel = panel.filter(pl.col("permno").is_in(keep))
        filings = filings.filter(pl.col("permno").is_in(keep))
    return panel, factors, filings


def short_eligible_mask(df, short_me_q, cfg):
    """Short-eligible expr: me_pct >= short_me_q, dolvol_pct >= short_dolvol_q, zero-trades <= universe median.
    Use as df.with_columns(short_eligible=short_eligible_mask(df, q, cfg)); df is unused (expression-based)."""
    return ((pl.col("me_pct") >= short_me_q) & (pl.col("dolvol_pct") >= cfg["short_dolvol_q"])
            & (pl.col("zt_raw") <= pl.col("zt_raw").median().over("eom"))).fill_null(False)


def build_universe(panel, cfg):
    """Step 2: per month, |prc| >= min and market_equity above the month's quantile (all stocks); raw copies kept."""
    me = pl.col("market_equity")
    df = panel.with_columns(
        prc_raw=pl.col("prc"), me_raw=me, dolvol_raw=pl.col("dolvol_126d"), zt_raw=pl.col("zero_trades_126d"),
        me_pct=me.rank("average").over("eom") / me.count().over("eom"),
        _cut=me.quantile(cfg["universe_me_q"]).over("eom"))
    df = df.filter((pl.col("prc").abs() >= cfg["min_abs_prc"]) & (me > pl.col("_cut"))).drop("_cut")
    return df.with_columns(
        dolvol_pct=pl.col("dolvol_raw").rank("average").over("eom") / pl.col("dolvol_raw").count().over("eom"),
        zt_pct=pl.col("zt_raw").rank("average").over("eom") / pl.col("zt_raw").count().over("eom"),
    ).with_columns(short_eligible=short_eligible_mask(None, cfg["short_me_q"], cfg))


def preprocess(univ, factors, cfg):
    """Step 3: missing flags from raw nulls (train rows), template rank to [-1,1] per month, nulls -> 0, sector."""
    train = univ.filter(pl.col("target_month") <= pl.lit("2018-12-31").str.to_date())
    miss = train.select([pl.col(c).is_null().mean() for c in factors]).row(0)
    flag_vars = [c for c, mm in zip(factors, miss) if mm is not None and mm > cfg["missing_flag_threshold"]]
    flag_cols = [c + "_miss" for c in flag_vars]
    out = univ.with_columns([pl.col(c).is_null().cast(pl.Int8).alias(c + "_miss") for c in flag_vars])

    def rk(c):  # template: dense rank - 1, / month max, *2 - 1; max == 0 -> 0; nulls -> 0
        r = pl.col(c).rank("dense").over("eom") - 1
        mx = r.max().over("eom")
        return pl.when(mx > 0).then(r / mx * 2 - 1).otherwise(0.0).fill_null(0.0).alias(c)
    out = out.with_columns([rk(c) for c in factors]).with_columns(sector=pl.col("gics").str.slice(0, 2).fill_null("NA"))
    return out, flag_cols


# ===== src/gru.py =====
"""
src/gru.py - Step 4: GRU autoencoder on 11 month-to-month changes of ranked features (trained <= 2018-11, then frozen).
"""
import copy
import numpy as np
import polars as pl
import torch
import torch.nn as nn


class _GruAE(nn.Module):
    """1-layer GRU encoder (hidden 64) -> linear to d; GRU decoder reconstructs the sequence from z."""
    def __init__(self, n_feat, d, hidden, seq):
        super().__init__()
        self.seq = seq
        self.enc, self.to_z = nn.GRU(n_feat, hidden, batch_first=True), nn.Linear(hidden, d)
        self.dec, self.out = nn.GRU(d, hidden, batch_first=True), nn.Linear(hidden, n_feat)

    def encode(self, x):
        return self.to_z(self.enc(x)[1][0])

    def forward(self, x):
        z = self.encode(x)
        return self.out(self.dec(z[:, None, :].expand(-1, self.seq, -1))[0]), z


def _gru_windows(df, factors, seq):
    """Dense (permno, month, feat) changes D and validity V; row indices (p, m) and valid-change counts per row."""
    mi = (df["eom"].dt.year() * 12 + df["eom"].dt.month() - 1).to_numpy().astype(np.int64)
    m = mi - (mi.min() - seq)  # pad so every window exists
    p_ids, p = np.unique(df["permno"].to_numpy(), return_inverse=True)
    X = np.full((len(p_ids), m.max() + 1, len(factors)), np.nan, np.float32)
    X[p, m] = df.select(factors).to_numpy().astype(np.float32)
    pres = ~np.isnan(X[:, :, 0])
    V = np.zeros(pres.shape, bool)
    V[:, 1:] = pres[:, 1:] & pres[:, :-1]  # change valid only between calendar-consecutive present months
    D = np.zeros_like(X)
    D[:, 1:] = np.where(V[:, 1:, None], X[:, 1:] - X[:, :-1], 0.0)
    nvalid = V[p[:, None], m[:, None] + np.arange(-seq + 1, 1)].sum(1)
    return D, V, p, m, nvalid


def _gru_batch(D, V, p, m, seq, dev):
    ix = m[:, None] + np.arange(-seq + 1, 1)
    return (torch.from_numpy(D[p[:, None], ix]).to(dev),
            torch.from_numpy(V[p[:, None], ix]).to(dev).float().unsqueeze(-1))


def _gru_loss(model, x, mask):
    xh, _ = model(x)
    return (mask * (xh - x) ** 2).sum() / (mask.sum() * x.shape[-1]).clamp(min=1)  # masked MSE


def gru_embeddings(df, factors, d, cfg):
    """Train on eom <= 2018-11, early-stop on 2019-2020 loss, pick weight decay, embed all (permno, eom)."""
    seq, dev, bs = cfg["gru_seq_len"], cfg["device"], cfg["gru_batch"]
    df = df.sort(["permno", "eom"])
    D, V, p, m, nvalid = _gru_windows(df, factors, seq)
    ok = nvalid >= cfg["gru_min_valid"]
    eom = df["eom"]
    tr_end = pl.Series([cfg["gru_train_end_eom"]]).str.to_date()[0]
    v0, v1 = [pl.Series([s]).str.to_date()[0] for s in cfg["gru_val_eom"]]
    tr = np.where(ok & (eom <= tr_end).to_numpy())[0]
    va = np.where(ok & ((eom >= v0) & (eom <= v1)).to_numpy())[0]
    if len(va) == 0:
        va = tr
    wd_losses, best = {}, None
    for wd in cfg["gru_wd_grid"]:
        torch.manual_seed(cfg["seed"])
        rng = np.random.default_rng(cfg["seed"])
        model = _GruAE(len(factors), d, cfg["gru_hidden"], seq).to(dev)
        opt = torch.optim.AdamW(model.parameters(), lr=cfg["gru_lr"], weight_decay=wd)
        best_l, best_sd, bad = np.inf, None, 0
        for _ in range(cfg["gru_max_epochs"]):
            model.train()
            perm = rng.permutation(tr)
            for i in range(0, len(perm), bs):
                b = perm[i:i + bs]
                x, mk = _gru_batch(D, V, p[b], m[b], seq, dev)
                opt.zero_grad()
                _gru_loss(model, x, mk).backward()
                nn.utils.clip_grad_norm_(model.parameters(), cfg["gru_clip"])
                opt.step()
            model.eval()
            with torch.no_grad():  # val loss: mean masked MSE over batches, weighted by batch size
                tot = sum(_gru_loss(model, *_gru_batch(D, V, p[va[i:i + bs]], m[va[i:i + bs]], seq, dev)).item()
                          * len(va[i:i + bs]) for i in range(0, len(va), bs)) / len(va)
            if tot < best_l - 1e-9:
                best_l, best_sd, bad = tot, copy.deepcopy(model.state_dict()), 0
            else:
                bad += 1
                if bad >= cfg["gru_patience"]:
                    break
        wd_losses[wd] = best_l
        if best is None or best_l < best[0]:
            best = (best_l, wd, best_sd)
    model = _GruAE(len(factors), d, cfg["gru_hidden"], seq).to(dev)
    model.load_state_dict(best[2])
    model.eval()
    emb = np.full((len(df), d), np.nan, np.float32)
    idx = np.where(ok)[0]
    with torch.no_grad():
        for i in range(0, len(idx), bs):
            b = idx[i:i + bs]
            emb[b] = model.encode(_gru_batch(D, V, p[b], m[b], seq, dev)[0]).cpu().numpy()
    out = df.select("permno", "eom").with_columns([pl.Series(f"gru_{j + 1}", emb[:, j]) for j in range(d)])
    return out, {"d": d, "best_wd": best[1], "val_loss": best[0], "wd_losses": wd_losses}


# ===== src/text.py =====
"""
src/text.py - Steps 6-7: 8-K event flags and FinBERT tone features per (permno, eom).
"""
import re
import numpy as np
import polars as pl
import torch


def _txt_idx(col="eom"):
    """Calendar month index (year*12 + month) of a Date expression."""
    c = pl.col(col)
    return c.dt.year().cast(pl.Int32) * 12 + c.dt.month().cast(pl.Int32)


def _txt_trailing(keys, monthly, offsets, aggs):
    """For each key (permno, eom): aggregate `monthly` (permno, idx, cols) over calendar months idx-o, o in offsets."""
    k = keys.select("permno", "eom").with_columns(_txt_idx().alias("idx"))
    parts = [k.with_columns((pl.col("idx") - o).alias("_j")) for o in offsets]
    k = pl.concat(parts).join(monthly.rename({"idx": "_j"}), on=["permno", "_j"], how="inner")
    return k.group_by("permno", "eom").agg(*aggs)


def event_flags(filings, keys, cfg):
    """Step 6: has_filing, n_filings, item_* (month t) and hist_* (12-month trailing counts, months t-11..t)."""
    ic = lambda it: it.replace(".", "_")
    f = filings.select("permno", "items", pl.col("filing_date").dt.month_end().alias("eom"))
    f = f.with_columns(
        [pl.col("items").list.contains(it).fill_null(False).cast(pl.Int8).alias(f"item_{ic(it)}") for it in cfg["items_flag"]]
        + [pl.col("items").list.contains(it).fill_null(False).cast(pl.Int8).alias(f"hist_{ic(it)}")
           for it in cfg["items_hist"]]
    )
    m = f.group_by("permno", "eom").agg(
        pl.len().alias("n_filings"),
        *[pl.col(f"item_{ic(it)}").max() for it in cfg["items_flag"]],
        *[pl.col(f"hist_{ic(it)}").sum().alias(f"hist_{ic(it)}") for it in cfg["items_hist"]],
    )
    cur = ["n_filings"] + [f"item_{ic(it)}" for it in cfg["items_flag"]]
    out = keys.select("permno", "eom").join(m.select("permno", "eom", *cur), on=["permno", "eom"], how="left")
    out = out.with_columns(pl.col("n_filings").is_not_null().cast(pl.Int8).alias("has_filing"))
    # history: sum monthly counts over t-11..t (calendar months); 0 when no filings in the window
    hc = [f"hist_{ic(it)}" for it in cfg["items_hist"]]
    h = _txt_trailing(keys, m.with_columns(_txt_idx().alias("idx")).select("permno", "idx", *hc), range(12),
                      [pl.col(c).sum() for c in hc])
    out = out.join(h, on=["permno", "eom"], how="left").with_columns([pl.col(c).fill_null(0) for c in hc])
    return out.select("permno", "eom", "has_filing", *cur, *hc)


# ---------------------------------------------------------------- FinBERT (step 7)
def _txt_load_model(cfg):
    """Returns (tokenizer, model in eval mode on cfg['device']). Separate so tests can replace it."""
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    tok = AutoTokenizer.from_pretrained(cfg["finbert_model"], use_fast=True)
    tok.model_max_length = int(1e9)  # we chunk manually; silence the length warning
    model = AutoModelForSequenceClassification.from_pretrained(cfg["finbert_model"]).to(cfg["device"]).eval()
    return tok, model


def _txt_anonymise(text, names, tickers):
    """Remove company names/tickers (word boundaries; names case-insensitive, tickers ALWAYS case-sensitive so ALL/NOW/FOR keep common words)."""
    def pat(words, flags):
        words = sorted({w.strip() for w in words if w and w.strip()}, key=len, reverse=True)
        if not words:
            return None
        return re.compile(r"(?<!\w)(?:" + "|".join(re.escape(w) for w in words) + r")(?!\w)", flags)
    ci = pat(list(names), re.IGNORECASE)
    cs = pat(list(tickers), 0)
    for p in (ci, cs):
        if p is not None:
            text = p.sub(" ", text)
    return text


def _txt_score_docs(docs, tok, model, cfg):
    """docs: list of clean texts -> list of (tone_mean, tone_min) (None, None if no tokens). Chunks sorted by length."""
    size, max_ch, bs = cfg["finbert_chunk_tokens"] - 2, cfg["finbert_max_chunks"], cfg["finbert_batch"]
    id2l = {int(i): str(l).lower() for i, l in model.config.id2label.items()}
    pos = next(i for i, l in id2l.items() if l.startswith("pos"))
    neg = next(i for i, l in id2l.items() if l.startswith("neg"))
    chunks = []  # (doc index, token ids)
    for s in range(0, len(docs), 64):
        enc = tok(docs[s:s + 64], add_special_tokens=False, truncation=False)["input_ids"]
        for j, ids in enumerate(enc):
            for c in range(0, min(len(ids), size * max_ch), size):
                chunks.append((s + j, ids[c:c + size]))
    order = sorted(range(len(chunks)), key=lambda i: len(chunks[i][1]))
    tones = np.zeros(len(chunks))
    dev = cfg["device"]
    for b in range(0, len(order), bs):
        idx = order[b:b + bs]
        L = max(len(chunks[i][1]) for i in idx) + 2
        ids = torch.full((len(idx), L), tok.pad_token_id, dtype=torch.long)
        mask = torch.zeros((len(idx), L), dtype=torch.long)
        for r, i in enumerate(idx):
            seq = [tok.cls_token_id] + chunks[i][1] + [tok.sep_token_id]
            ids[r, :len(seq)] = torch.tensor(seq)
            mask[r, :len(seq)] = 1
        with torch.inference_mode(), torch.autocast(device_type="cuda", dtype=torch.bfloat16, enabled=(dev == "cuda")):
            logits = model(input_ids=ids.to(dev), attention_mask=mask.to(dev)).logits
        p = torch.softmax(logits.float(), dim=-1).cpu().numpy()
        tones[idx] = p[:, pos] - p[:, neg]
    per = [[] for _ in docs]
    for (d, _), t in zip(chunks, tones):
        per[d].append(t)
    return [(float(np.mean(t)), float(np.min(t))) if t else (None, None) for t in per]


def finbert_doc_tones(filings, panel, cfg, save_every=2000):
    """Step 7: per-filing FinBERT tone (mean, min over <= 8 chunks), cached by document_id."""
    path = cfg["cache_dir"] / ("finbert_docs_smoke.parquet" if cfg["smoke"] else "finbert_docs.parquet")
    schema = {"document_id": pl.String, "tone_mean": pl.Float64, "tone_min": pl.Float64}
    cache = pl.read_parquet(path) if path.exists() else pl.DataFrame(schema=schema)
    f = filings.with_columns(pl.col("filing_date").dt.month_end().alias("eom"))
    pk = panel.select("permno", "eom").unique()
    f = f.join(pk, on=["permno", "eom"], how="semi")
    todo = f.filter(~pl.col("document_id").is_in(cache["document_id"].implode())).sort("document_id")
    if cfg.get("finbert_max_filings") is not None:
        todo = todo.head(cfg["finbert_max_filings"])
    if todo.height:
        # panel names/tickers for that permno-eom, used as extra anonymisation terms
        extra = {}
        if {"company_name", "ticker"} <= set(panel.columns):
            for r in panel.select("permno", "eom", "company_name", "ticker").iter_rows():
                extra[(r[0], r[1])] = (r[2], r[3])
        tok, model = _txt_load_model(cfg)
        todo = todo.select("document_id", "permno", "eom", "text", "company_name", "ticker")
        for s in range(0, todo.height, save_every):
            rows = todo.slice(s, save_every).to_dicts()
            docs = []
            for r in rows:
                pn, pt = extra.get((r["permno"], r["eom"]), (None, None))
                docs.append(_txt_anonymise(r["text"] or "", [r["company_name"], pn], [r["ticker"], pt]))
            sc = _txt_score_docs(docs, tok, model, cfg)
            new = pl.DataFrame({"document_id": [r["document_id"] for r in rows],
                                "tone_mean": [x[0] for x in sc], "tone_min": [x[1] for x in sc]}, schema=schema)
            cache = pl.concat([cache, new])
            cache.write_parquet(path)  # incremental save: a crash keeps progress
    return cache.filter(pl.col("document_id").is_in(f["document_id"].implode()))


def tone_features(filings, doc_tones, keys, cfg):
    """Per stock-month tone_mean, tone_min, tone_surprise = tone_mean - mean of monthly tone_mean over t-12..t-1."""
    f = (filings.select("document_id", "permno", pl.col("filing_date").dt.month_end().alias("eom"))
         .join(doc_tones, on="document_id", how="inner").drop_nulls("tone_mean"))
    m = f.group_by("permno", "eom").agg(pl.col("tone_mean").mean(), pl.col("tone_min").min())
    h = _txt_trailing(keys, m.with_columns(_txt_idx().alias("idx")).select("permno", "idx", "tone_mean"),
                      range(1, 13), [pl.col("tone_mean").mean().alias("_hist")])
    out = keys.select("permno", "eom").join(m, on=["permno", "eom"], how="left").join(h, on=["permno", "eom"], how="left")
    return out.select("permno", "eom", "tone_mean", "tone_min", (pl.col("tone_mean") - pl.col("_hist")).alias("tone_surprise"))


# ===== src/kalman.py =====
"""
src/kalman.py - Step 8: Kalman-filtered stock betas (4 noisy beta measures -> one state).
beta_t - m_t = phi (beta_{t-1} - m_{t-1}) + N(0,q);  m_t = sector median of beta_60m.
Sequential scalar updates per observation (own R_j); phi, q, R_j by exact Gaussian MLE on eom <= 2018-12, then frozen.
"""
from datetime import date

import numpy as np
import polars as pl
from scipy.optimize import minimize


def _kalman_grid(panel, cfg):
    """Dense arrays: permnos, month-ends, Y (n,T,J) observations, m (n,T) prior mean, first (n,) first month index, row index."""
    obs = cfg["kalman_obs"]
    df = panel.select("permno", "eom", "gics", *obs).with_columns(
        pl.col("gics").str.slice(0, 2).alias("sector"))
    months = pl.date_range(df["eom"].min(), df["eom"].max(), "1mo", eager=True).dt.month_end()
    permnos = df["permno"].unique().sort()
    pi = permnos.search_sorted(df["permno"]).to_numpy()
    ti = months.search_sorted(df["eom"]).to_numpy()
    n, T = len(permnos), len(months)
    Y = np.full((n, T, len(obs)), np.nan)
    for j, c in enumerate(obs):
        Y[pi, ti, j] = df[c].cast(pl.Float64).fill_nan(None).to_numpy(allow_copy=True)
    # prior mean: sector median of beta_60m per month, all-stock median where the sector median is null
    med = df.group_by("eom", "sector").agg(pl.col("beta_60m").median().alias("m_sec")).join(
        df.group_by("eom").agg(pl.col("beta_60m").median().alias("m_all")), on="eom")
    sec_of = (df.sort("eom").group_by("permno").agg(pl.col("sector").drop_nulls().first())
              .sort("permno"))["sector"]                                  # stock's first known sector
    secs = sorted(set(sec_of.drop_nulls().to_list()))
    sidx = np.array([secs.index(s) if s is not None else -1 for s in sec_of.to_list()])
    M_sec = np.full((len(secs) + 1, T), np.nan)                           # last row (idx -1) = no sector
    M_all = np.full(T, np.nan)
    mi = months.search_sorted(med["eom"]).to_numpy()
    M_all[mi] = med["m_all"].to_numpy()
    for s, t, v in zip(med["sector"].to_list(), mi, med["m_sec"].to_numpy()):
        if s is not None:
            M_sec[secs.index(s), t] = v
    M_all = np.where(np.isnan(M_all), np.nanmedian(M_all), M_all)
    m = np.where(np.isnan(M_sec[sidx]), M_all[None, :], M_sec[sidx])
    first = np.full(n, T)
    np.minimum.at(first, pi, ti)
    return permnos, months, Y, m, first, pi, ti


def _kalman_filter(Y, m, first, theta, t_end=None, full=False):
    """Vectorised-over-stocks filter. Returns loglik (and state, var, has_obs grids if full)."""
    phi = 1 / (1 + np.exp(-theta[0])); q = np.exp(theta[1]); R = np.exp(theta[2:])
    n, T, J = Y.shape
    T = T if t_end is None else t_end
    d = np.zeros(n); P = np.full(n, q / (1 - phi ** 2)); seen = np.zeros(n, bool)
    ll = 0.0
    out = np.zeros((3, n, T)) if full else None
    for t in range(T):
        if t > 0:                                                         # predict (also bridges missing months)
            d = phi * d                                                   # deviations from m_t
            P = phi ** 2 * P + q
        start = first == t                                                # initialise at first month: d=0, P=q/(1-phi^2)
        d = np.where(start, 0.0, d); P = np.where(start, q / (1 - phi ** 2), P)
        active = first <= t
        for j in range(J):
            y = Y[:, t, j] - m[:, t]
            ok = active & ~np.isnan(y)
            S = P + R[j]
            v = np.where(ok, y - d, 0.0)
            ll += -0.5 * np.sum(np.where(ok, np.log(2 * np.pi * S) + v ** 2 / S, 0.0))
            K = np.where(ok, P / S, 0.0)
            d = d + K * v; P = (1 - K) * P; seen |= ok
        if full:
            out[0, :, t], out[1, :, t], out[2, :, t] = d + m[:, t], P, seen
    return (ll, out) if full else ll


def kalman_betas(panel, cfg, r_floor=None):
    """-> (DataFrame[permno, eom, beta_kf, beta_var], params). Panel = raw (unranked) betas.
    r_floor: optional lower bound on every observation noise variance R_j (None = unconstrained MLE)."""
    permnos, months, Y, m, first, pi, ti = _kalman_grid(panel, cfg)
    J = Y.shape[2]
    t_fit = int((months <= date.fromisoformat(cfg["kalman_fit_end_eom"])).sum())
    lo, hi = np.nanpercentile(Y[:, :t_fit], 1, axis=(0, 1)), np.nanpercentile(Y[:, :t_fit], 99, axis=(0, 1))
    Y = np.clip(Y, lo, hi)                       # winsorise at the fit-sample 1/99 pct: raw betas have +-1e4 outliers (not in spec)
    x0 = np.array([2.0, np.log(0.02)] + [np.log(0.05)] * J)
    # R floor (not in spec): unconstrained MLE drives R(betabab_1260d) to its lower bound, so beta_kf copies that
    # 5-year shrunk beta; the step-10 beta check found the validation book's realised beta clearly nonzero.
    r_lo = -12 if r_floor is None else float(np.log(r_floor))
    if r_floor is not None:
        x0[2:] = np.maximum(x0[2:], r_lo)
    res = minimize(lambda th: -_kalman_filter(Y, m, first, th, t_fit), x0, method="L-BFGS-B",
                   bounds=[(-8, 8), (-12, 3)] + [(r_lo, 3)] * J)
    th = res.x
    params = {"phi": float(1 / (1 + np.exp(-th[0]))), "q": float(np.exp(th[1])),
              "R": {c: float(np.exp(r)) for c, r in zip(cfg["kalman_obs"], th[2:])}, "loglik": float(-res.fun),
              "r_floor": r_floor}
    _, out = _kalman_filter(Y, m, first, th, full=True)
    kf, var, seen = out[0, pi, ti], out[1, pi, ti], out[2, pi, ti].astype(bool)
    b60 = Y[pi, ti, cfg["kalman_obs"].index("beta_60m")]
    kf = np.where(seen, kf, np.where(np.isnan(b60), m[pi, ti], b60))      # no data yet -> beta_60m, else m_t
    df = panel.select("permno", "eom").with_columns(pl.Series("beta_kf", kf), pl.Series("beta_var", var))
    return df, params


# ===== src/ranker.py =====
"""
src/ranker.py - Step 5: XGBRanker (rank:pairwise, qid = eom) with walk-forward windows, plus the Ridge baseline.
Scores are cross-sectional only; ret_hat comes from a rank regression fitted on validation scores of the train-only model.
"""
import calendar
from datetime import date

import numpy as np
import polars as pl
import xgboost as xgb
from sklearn.linear_model import Ridge


def _rk_me(s):
    """'YYYY-MM' -> month-end date."""
    y, m = int(s[:4]), int(s[5:7])
    return date(y, m, calendar.monthrange(y, m)[1])


def windows(cfg):
    """One dict per test year, by TARGET month: train 2015-02..Y-3, val Y-2..Y-1, test Y (2026 ends at last_test_month)."""
    first, last = _rk_me(cfg["first_train_month"]), _rk_me(cfg["last_test_month"])
    return [dict(year=y, train=(first, date(y - 3, 12, 31)), val=(date(y - 2, 1, 31), date(y - 1, 12, 31)),
                 test=(date(y, 1, 31), min(date(y, 12, 31), last))) for y in cfg["test_years"]]


def rank_ic(pred, cfg=None):
    """Monthly Spearman IC of score vs ret_exc_lead1m (Pearson on within-month average ranks); null targets dropped."""
    return (pred.drop_nulls("ret_exc_lead1m").group_by("eom")
            .agg(pl.corr(pl.col("score").rank(), pl.col("ret_exc_lead1m").rank()).alias("ic")).sort("eom"))


def _rk_mean_ic(eom, score, y):
    """Mean monthly rank IC from numpy arrays (months with undefined IC are skipped)."""
    ic = rank_ic(pl.DataFrame({"eom": eom, "score": score, "ret_exc_lead1m": y}))["ic"].drop_nans().drop_nulls()
    return float(ic.mean()) if len(ic) else float("nan")


def _rk_labels(eom, y):
    """Within-month decile 0-9 of y: floor(10*(rank_ordinal-1)/n)."""
    d = pl.DataFrame({"eom": eom, "y": y}).with_columns(
        (10 * (pl.col("y").rank("ordinal").over("eom") - 1) // pl.len().over("eom")).cast(pl.Int32).alias("l"))
    return d["l"].to_numpy()


def _rk_shuffle(eom, y, seed):
    """Permute y within each month (rows are sorted by eom, so blocks stay in place)."""
    order = np.lexsort((np.random.default_rng(seed).random(len(y)), eom.to_numpy()))
    return y[order]


def _rk_ranks(eom, score):
    """Within-month rank of score scaled to [-1, 1]."""
    d = pl.DataFrame({"eom": eom, "s": score}).with_columns(
        r=pl.col("s").rank().over("eom"), n=pl.len().over("eom"))
    return d.select(pl.when(pl.col("n") > 1).then((pl.col("r") - 1) / (pl.col("n") - 1) * 2 - 1).otherwise(0.0))["r"].to_numpy()


def _rk_mat(d, features):
    return d.select(features).cast(pl.Float32).to_numpy()  # nulls -> NaN (XGBoost handles them natively)


def fit_predict_year(df, features, win, cfg, model="xgb", shuffle=False):
    """Tune on val (train-only fits), refit on train+val, predict the test year. Returns (test_pred, val_pred, info)."""
    df = df.sort(["eom", "permno"])
    rng = lambda w: (pl.col("target_month") >= w[0]) & (pl.col("target_month") <= w[1])
    has_y = pl.col("ret_exc_lead1m").is_not_null()
    tr, va = df.filter(rng(win["train"]) & has_y), df.filter(rng(win["val"]) & has_y)
    te = df.filter(rng(win["test"]))
    va_all = df.filter(rng(win["val"]))  # incl. null-target rows: val_pred must cover every validation month-row
    ytr, yva = tr["ret_exc_lead1m"].to_numpy(), va["ret_exc_lead1m"].to_numpy()
    if shuffle:  # leakage test: destroy the label-feature link in train AND val
        ytr, yva = _rk_shuffle(tr["eom"], ytr, cfg["seed"]), _rk_shuffle(va["eom"], yva, cfg["seed"] + 1)
    Xtr, Xva, Xte = _rk_mat(tr, features), _rk_mat(va, features), _rk_mat(te, features)
    Xall, yall = np.vstack([Xtr, Xva]), np.concatenate([ytr, yva])
    eall = pl.concat([tr["eom"], va["eom"]])
    kw = dict(device="cuda") if cfg["device"] == "cuda" and xgb.build_info().get("USE_CUDA") else {}

    def _xgb(depth, trees, X, y, e):
        m = xgb.XGBRanker(**cfg["xgb_fixed"], max_depth=depth, n_estimators=trees, random_state=cfg["seed"], **kw)
        m.fit(X, _rk_labels(e, y), qid=e.cast(pl.Int32).to_numpy())
        return m

    grid, best, val_score, best_m = {}, (-np.inf, None, None), None, None
    if model == "xgb":
        for depth in cfg["xgb_depth_grid"]:
            m = _xgb(depth, cfg["xgb_max_trees"], Xtr, ytr, tr["eom"])
            for k in range(cfg["xgb_eval_every"], cfg["xgb_max_trees"] + 1, cfg["xgb_eval_every"]):
                s = m.predict(Xva, iteration_range=(0, k))
                ic = _rk_mean_ic(va["eom"], s, yva)
                grid[f"{depth}_{k}"] = ic
                if ic > best[0]:
                    best, val_score, best_m = (ic, depth, k), s, m
        final = _xgb(best[1], best[2], Xall, yall, eall)
        te_score = final.predict(Xte)
        va_all_score = best_m.predict(_rk_mat(va_all, features), iteration_range=(0, best[2]))
    else:  # ridge baseline on the features (template: Ridge on the 147 characteristics)
        Xtr0, Xva0, Xte0, Xall0 = (np.nan_to_num(x) for x in (Xtr, Xva, Xte, Xall))
        for a in cfg["ridge_alpha_grid"]:
            rm = Ridge(alpha=a).fit(Xtr0, ytr)
            s = rm.predict(Xva0)
            ic = _rk_mean_ic(va["eom"], s, yva)
            grid[str(a)] = ic
            if ic > best[0]:
                best, val_score, best_m = (ic, a, None), s, rm
        te_score = Ridge(alpha=best[1]).fit(Xall0, yall).predict(Xte0)
        va_all_score = best_m.predict(np.nan_to_num(_rk_mat(va_all, features)))

    # ret_hat: linear regression of realised return on the within-month score rank, fitted on val scores of the train-only model
    slope, icpt = np.polyfit(_rk_ranks(va["eom"], val_score), yva, 1)
    out = lambda d, s: d.select("permno", "eom").with_columns(
        score=pl.Series(s, dtype=pl.Float64),
        ret_hat=pl.Series(icpt + slope * _rk_ranks(d["eom"], s), dtype=pl.Float64))
    info = dict(year=win["year"], model=model, best_depth=best[1] if model == "xgb" else None,
                best_trees=best[2], val_ic=best[0], grid=grid,
                train_max_target=max(tr["target_month"].max(), va["target_month"].max()))  # step 11 check
    if model == "ridge":
        info["best_alpha"] = best[1]
    return out(te, te_score), out(va_all, va_all_score), info


def run_schedule(df, features, cfg, model="xgb", shuffle=False):
    """Loop over test years. Returns (preds, val_2021, infos)."""
    tests, infos, val_2021 = [], [], None
    for w in windows(cfg):
        t, v, i = fit_predict_year(df, features, w, cfg, model, shuffle)
        tests.append(t); infos.append(i)
        if w["year"] == 2021:
            val_2021 = v
    return pl.concat(tests), val_2021, infos


# ===== src/risk.py =====
"""
src/risk.py - factor risk model (not in spec): monthly cross-sectional OLS factor returns on
[intercept, ranked characteristics, sector dummies]; F_t = trailing covariance of factor returns known at eom t.
"""
import numpy as np
import polars as pl


def risk_exposures(mdf, sectors, cfg):
    """One month -> n x k exposures: intercept, cfg risk_factors (nulls -> 0), sector dummies for `sectors`."""
    cols = mdf.select([pl.col(c).fill_nan(None).fill_null(0.0) for c in cfg["risk_factors"]]).to_numpy().astype(float)
    sec = mdf["sector"].fill_null("NA").to_numpy()
    D = (sec[:, None] == np.array(sectors)[None, :]).astype(float)
    return np.hstack([np.ones((len(mdf), 1)), cols, D])


def risk_model(frame, cfg):
    """frame: permno, eom, sector, ret_exc_lead1m, risk factors -> {"sectors": [...], "L": {eom: k x k Cholesky of F_t}}."""
    sectors = sorted(frame["sector"].fill_null("NA").unique().to_list())
    fs = {}                                                                 # eom s -> factor return, realised in month s+1
    for (s,), g in frame.filter(pl.col("ret_exc_lead1m").is_not_null()).sort("eom").group_by("eom", maintain_order=True):
        X = risk_exposures(g, sectors, cfg)
        fs[s] = np.linalg.lstsq(X, g["ret_exc_lead1m"].to_numpy().astype(float), rcond=None)[0]
    eoms = sorted(fs)
    known = dict(zip(eoms, pl.Series(eoms).dt.offset_by("1mo").dt.month_end().to_list()))   # f_s known at eom s+1
    L = {}
    for t in sorted(frame["eom"].unique().to_list()):
        past = [fs[s] for s in eoms if known[s] <= t][-cfg["risk_window"]:]
        if len(past) < cfg["risk_min_months"]:
            continue
        F = np.cov(np.array(past), rowvar=False)
        k = F.shape[0]                                     # few months vs ~22 factors: shrink toward avg variance
        F = 0.9 * F + 0.1 * np.trace(F) / k * np.eye(k) + 1e-8 * np.eye(k)
        L[t] = np.linalg.cholesky(F)
    return {"sectors": sectors, "L": L}


# ===== src/optimizer.py =====
"""
src/optimizer.py - Step 9: long/short portfolio optimiser (cvxpy + Clarabel), one convex problem per month.
w = wL - wS over the UNION of long candidates (top n by score) and short candidates (bottom n of the short-eligible subset).
"""
import cvxpy as cp
import numpy as np
import polars as pl


def optimize_month(mdf, w_prev, lam_tc, lam_beta, cfg, lam_risk=0.0, lam_fac=0.0, risk=None):
    """mdf: one month with permno, score, short_eligible, beta_kf, beta_var, sector [, size_z] -> (weights dict, info dict); risk = (sectors, L) adds lam_fac * w'X F X'w."""
    d = mdf.with_columns(pl.col("sector").fill_null("NA")).sort("permno").with_columns(
        ((pl.col("score") - pl.col("score").mean()) / pl.col("score").std()).fill_nan(0.0).fill_null(0.0).alias("s"),
        pl.col("beta_kf").fill_nan(None).fill_null(pl.col("beta_kf").median()),
        pl.col("beta_var").fill_nan(None).fill_null(pl.col("beta_var").median()))
    has_size = "size_z" in d.columns                                       # not in spec: size neutrality only if present
    if has_size:
        d = d.with_columns(pl.col("size_z").fill_nan(None).fill_null(0.0))
    long_ids = set(d.sort(["s", "permno"], descending=[True, False]).head(cfg["n_long_cand"])["permno"])
    short_ids = set(d.filter(pl.col("short_eligible") & ~pl.col("permno").is_in(long_ids))     # no name on both sides:
                    .sort(["s", "permno"]).head(cfg["n_short_cand"])["permno"])               # wL=wS would fake gross
    c = d.filter(pl.col("permno").is_in(long_ids | short_ids))
    ids = c["permno"].to_list(); n = len(ids)
    s, bk, bv = c["s"].to_numpy(), c["beta_kf"].to_numpy(), c["beta_var"].to_numpy()
    sz = c["size_z"].to_numpy() if has_size else None
    ubL = np.array([cfg["max_weight"] if p in long_ids else 0.0 for p in ids])
    ubS = np.array([cfg["max_weight"] if p in short_ids else 0.0 for p in ids])
    G = (c["sector"].to_numpy()[None, :] == np.unique(c["sector"].to_numpy())[:, None]).astype(float)
    wp = np.clip(np.nan_to_num(np.array([w_prev.get(p, 0.0) for p in ids])), -cfg["max_weight"], cfg["max_weight"])
    dropped = sum(abs(v) for p, v in w_prev.items() if p not in set(ids))   # names that left the candidate set: sold to 0

    wL, wS = cp.Variable(n, nonneg=True), cp.Variable(n, nonneg=True)
    tol, band, sband = cp.Parameter(nonneg=True), cp.Parameter(nonneg=True), cp.Parameter(nonneg=True)
    w = wL - wS
    obj = s @ w - lam_tc * cp.norm1(w - wp) - lam_beta * (bv @ cp.square(w)) - lam_risk * cp.sum_squares(w)   # L2 risk penalty (not in spec); dropped-name sales are a constant
    cons = [cp.sum(wL) + cp.sum(wS) == cfg["gross"], cp.abs(cp.sum(w)) <= cfg["net_band"], wL <= ubL, wS <= ubS,
            cp.abs(bk @ w) <= tol, cp.abs(G @ w) <= band]
    if has_size:
        cons.append(cp.abs(sz @ w) <= sband)                               # not in spec: size-neutral book
    if lam_fac > 0 and risk is not None:
        obj = obj - lam_fac * cp.sum_squares(risk[1].T @ (risk_exposures(c, risk[0], cfg).T @ w))   # factor-risk penalty (not in spec)
    prob = cp.Problem(cp.Maximize(obj), cons)

    def solve(t_, b_, sb_):
        tol.value, band.value, sband.value = t_, b_, sb_
        try:
            prob.solve(solver=cp.CLARABEL)
        except cp.SolverError:
            return False                                                   # treated as a failed attempt
        if prob.status not in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE) or w.value is None:
            return False
        v = w.value                                                        # inaccurate solutions can hold garbage weights
        return bool(np.all(np.isfinite(v)) and np.abs(v).max() <= cfg["max_weight"] + 1e-4
                    and abs(np.abs(v).sum() - cfg["gross"]) <= 1e-3)

    t, b, sb, no_beta = cfg["beta_tol"], cfg["sector_band"], cfg["size_band"], 1e6
    if not solve(t, b, sb):
        # Not in spec: if the month is infeasible even with NO beta limit, the sector nets bind,
        # so widen the sector (and size) band in 0.05 steps first (logged), then relax beta from 0.02 as the spec says.
        while not solve(no_beta, b, sb):
            b += 0.05
            sb += 0.05
            if b > 2.0:                                                    # should not happen: save inputs, hold last book
                eom = mdf["eom"][0]
                path = cfg["cache_dir"] / f"optimizer_fail_{eom}.parquet"
                mdf.write_parquet(path)
                bad = {k: int((~np.isfinite(v)).sum()) for k, v in (("s", s), ("beta_kf", bk), ("beta_var", bv))}
                print(f"[optimizer] WARNING {eom}: infeasible ({prob.status}) even with sector band 2.0 and no beta limit; "
                      f"rows={d.height} long_cand={len(long_ids)} short_cand={len(short_ids)} non-finite={bad}; "
                      f"holding previous weights; inputs saved to {path}")
                return dict(w_prev), {"beta_tol": None, "sector_band": b, "size_band": sb, "status": "fallback_hold",
                                      "n_long": sum(v > 0 for v in w_prev.values()),
                                      "n_short": sum(v < 0 for v in w_prev.values()), "turnover": 0.0}
        while not solve(t, b, sb):                                           # spec: relax beta tolerance in 0.01 steps
            t += cfg["beta_tol_step"]                                      # terminates: feasible without a beta limit
    wv = np.where(np.abs(w.value) < 1e-7, 0.0, w.value)
    weights = {p: float(x) for p, x in zip(ids, wv) if x != 0.0}
    turnover = float(np.abs(wv - wp).sum() + dropped)
    return weights, {"beta_tol": round(t, 6), "sector_band": round(b, 6), "size_band": round(sb, 6), "status": prob.status, "n_long": int((wv > 0).sum()),
                     "n_short": int((wv < 0).sum()), "turnover": turnover}


def run_book(scored, lam_tc, lam_beta, cfg, lam_risk=0.0, lam_fac=0.0, rm=None):
    """scored: all months (permno, eom, score, short_eligible, beta_kf, beta_var, sector) -> (weights df, log)."""
    w_prev, rows, log = {}, [], []
    for (eom,), mdf in scored.sort("eom").group_by("eom", maintain_order=True):
        risk = (rm["sectors"], rm["L"][eom]) if rm is not None and eom in rm["L"] else None
        w, info = optimize_month(mdf, w_prev, lam_tc, lam_beta, cfg, lam_risk, lam_fac, risk)
        if info["beta_tol"] is not None and info["beta_tol"] > cfg["beta_tol"]:
            print(f"[optimizer] {eom}: beta tolerance relaxed to {info['beta_tol']:.2f}")
        if info["sector_band"] > cfg["sector_band"]:
            print(f"[optimizer] {eom}: sector band relaxed to {info['sector_band']:.2f} (infeasible at 0.10)")
        if info["size_band"] > cfg["size_band"]:
            print(f"[optimizer] {eom}: size band relaxed to {info['size_band']:.2f}")
        log.append({"eom": eom, **info})
        rows += [(p, eom, x) for p, x in w.items()]
        w_prev = w
    wdf = pl.DataFrame(rows, schema={"permno": pl.Int64, "eom": pl.Date, "weight": pl.Float64}, orient="row")
    return wdf, log


# ===== src/metrics.py =====
"""
src/metrics.py - Step 13 numbers: monthly book returns, summary statistics, OOS R2 and rank-IC summary.
Convention: weights at formation month-end t are realised with ret_exc_lead1m (excess return of month t+1).
"""
import numpy as np
import pandas as pd
import polars as pl
import statsmodels.api as sm


def load_market(cfg) -> pl.DataFrame:
    """TB3MS (annualised %) and S&P 500 monthly total return keyed on month-end eom."""
    f = cfg["data_files"]
    tb = pl.read_csv(f["tb3ms"], try_parse_dates=True).select(pl.col("eom").cast(pl.Date), "tb3ms")
    sp = pl.read_csv(f["sp500"], try_parse_dates=True).select(pl.col("eom").cast(pl.Date), "sp500_ret")
    return tb.join(sp, on="eom", how="full", coalesce=True).sort("eom")


def book_returns(weights, panel, market, cfg):
    """One row per formation month: returns, benchmark, legs, exposures, counts, turnover. Returns (rets, n_missing)."""
    w = weights.select("permno", "eom", "weight").join(
        panel.select("permno", "eom", "ret_exc_lead1m"), on=["permno", "eom"], how="left")
    n_missing = int(w["ret_exc_lead1m"].is_null().sum())
    w = w.with_columns(r=pl.col("ret_exc_lead1m").fill_null(0.0)).with_columns(c=pl.col("weight") * pl.col("r"))
    g = w.group_by("eom").agg(
        long_leg=pl.col("c").filter(pl.col("weight") > 0).sum(),
        short_leg=pl.col("c").filter(pl.col("weight") < 0).sum(),
        gross=pl.col("weight").abs().sum(), net=pl.col("weight").sum(),
        n_long=(pl.col("weight") > 0).sum(), n_short=(pl.col("weight") < 0).sum()).sort("eom")
    # turnover = sum |w_t - w_{t-1}| over the union of names (absent = 0); first month starts from cash
    pw = w.to_pandas().pivot_table(index="eom", columns="permno", values="weight", aggfunc="sum").sort_index().fillna(0.0)
    to = pw.diff().abs().sum(axis=1)
    to.iloc[0] = pw.iloc[0].abs().sum()
    g = g.join(pl.DataFrame({"eom": pl.Series(to.index).cast(pl.Date), "turnover": to.values}), on="eom")
    mk = market.with_columns(eom=pl.col("eom").dt.offset_by("-1mo").dt.month_end()).select(  # key on formation month
        "eom", rf=pl.col("tb3ms") / 1200, sp500=pl.col("sp500_ret"))
    prem = cfg["premium_annual"] / 12
    rets = (g.join(mk, on="eom", how="left")
            .with_columns(Date=pl.col("eom").dt.offset_by("1mo").dt.month_start(),
                          excess=pl.col("long_leg") + pl.col("short_leg"))
            .with_columns(total=pl.col("rf") + pl.col("excess"), benchmark=pl.col("rf") + prem,
                          active=pl.col("excess") - prem)
            .select("eom", "Date", "total", "excess", "active", "long_leg", "short_leg", "benchmark", "sp500",
                    "gross", "net", "n_long", "n_short", "turnover", "rf"))
    return rets, n_missing


def _ir(a):
    sd = np.std(a, ddof=1)
    return float(np.sqrt(12) * np.mean(a) / sd) if sd > 0 else float("nan")


def _leg(r):
    """Arithmetic/geometric stats for one monthly return series."""
    n = len(r)
    cum = float(np.prod(1 + r) - 1)
    return {"mean_monthly": float(np.mean(r)), "ann_arith": float(np.mean(r) * 12),
            "cagr": float((1 + cum) ** (12 / n) - 1), "cumulative": cum}


def _mm(x):
    return {"avg": float(np.mean(x)), "min": float(np.min(x)), "max": float(np.max(x))}


def _maxdd(r):
    c = np.cumprod(1 + np.asarray(r))
    return float((c / np.maximum.accumulate(np.r_[1.0, c])[1:] - 1).min())


def summary_stats(rets, cfg) -> dict:
    """Headline statistics of the monthly book (see contract)."""
    d = rets.to_pandas()
    rf = d["rf"].values if "rf" in d else (d["benchmark"] - cfg["premium_annual"] / 12).values
    tot, exc, act, sp = d["total"].values, d["excess"].values, d["active"].values, d["sp500"].values
    sd_tot = np.std(tot - rf, ddof=1)
    out = {"n_months": len(d), "ir": _ir(act), "sharpe": float(np.sqrt(12) * np.mean(tot - rf) / sd_tot),
           "strategy": _leg(tot), "benchmark": _leg(d["benchmark"].values), "sp500": _leg(sp),
           "long_leg": _leg(d["long_leg"].values), "short_leg": _leg(d["short_leg"].values),
           "max_drawdown": _maxdd(tot), "sp500_max_drawdown": _maxdd(sp),
           "best_month": float(tot.max()), "worst_month": float(tot.min()),
           "hit_rate": float(np.mean((exc > 0) & (act > 0))),
           "gross": _mm(d["gross"]), "net": _mm(d["net"]), "turnover": _mm(d["turnover"]),
           "n_long": _mm(d["n_long"]), "n_short": _mm(d["n_short"]),
           "corr_sp500": float(np.corrcoef(tot, sp)[0, 1])}
    ols = sm.OLS(exc, sm.add_constant(sp - rf)).fit(cov_type="HAC", cov_kwds={"maxlags": cfg["nw_lags"]})
    out.update(alpha_monthly=float(ols.params[0]), alpha_annual=float(ols.params[0] * 12), alpha_t=float(ols.tvalues[0]),
               beta=float(ols.params[1]), beta_t=float(ols.tvalues[1]))
    yr = d["Date"].dt.year
    cal = lambda x: pd.Series(x).groupby(yr.values).apply(lambda s: float(np.prod(1 + s) - 1))
    out["calendar_years"] = {str(y): {"strategy": v, "benchmark": float(cal(d["benchmark"].values)[y]),
                                      "sp500": float(cal(sp)[y])} for y, v in cal(tot).items()}
    return out


def oos_r2(pred) -> float:
    """Zero-benchmark OOS R2 = 1 - sum (r - r_hat)^2 / sum r^2 on rows with non-null target."""
    p = pred.drop_nulls(["ret_exc_lead1m", "ret_hat"])
    r, h = p["ret_exc_lead1m"].to_numpy(), p["ret_hat"].to_numpy()
    return float(1 - np.sum((r - h) ** 2) / np.sum(r ** 2))


def ic_summary(pred, cfg) -> dict:
    """Mean monthly Spearman rank IC of score vs target, ICIR = mean/std * sqrt(12)."""
    p = pred.drop_nulls(["ret_exc_lead1m", "score"]).to_pandas()
    ic = p.groupby("eom").apply(lambda g: g["score"].corr(g["ret_exc_lead1m"], method="spearman")).dropna()
    sd = ic.std(ddof=1)
    return {"mean_ic": float(ic.mean()), "icir": float(ic.mean() / sd * np.sqrt(12)) if sd > 0 else float("nan"),
            "n_months": int(len(ic))}


# ===== src/report.py =====
"""
src/report.py - Steps 13-14: performance pack (performance.json + charts) and submission files (holdings.csv, returns.csv).
Chart style ported from the AlphaBERT repo (src/evaluate.py): 10x5 figures, default tab colours, curves anchored at 0 before
the first month, zero lines in black, hurdle as red dashed line, titles end with "gross of trading costs, <period>".
"""
import json
import numpy as np
import pandas as pd
import polars as pl
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _rep_savefig(fig, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def _rep_line(series, title, path, hline=None, ylabel=None):
    fig, ax = plt.subplots(figsize=(10, 5))
    for label, s in series.items():
        ax.plot(s.index, s.values, label=label)
    if hline is not None:
        ax.axhline(hline, color="black", lw=0.8)
    if ylabel:
        ax.set_ylabel(ylabel)
    ax.set_title(title)
    if len(series) > 1:
        ax.legend()
    _rep_savefig(fig, path)


def _rep_labels(keys, panel, filings) -> pl.DataFrame:
    """keys[permno, eom] -> + ticker, company_name from the panel row; gaps filled from the 8-K row nearest in filing_date."""
    k = keys.join(panel.select("permno", "eom", "ticker", "company_name"), on=["permno", "eom"], how="left").sort("eom")
    for col in ["ticker", "company_name"]:
        if filings is None or col not in filings.columns:
            continue
        fl = filings.select("permno", "filing_date", pl.col(col).alias(col + "_8k")).drop_nulls().sort("filing_date")
        if fl.height:
            k = (k.join_asof(fl, left_on="eom", right_on="filing_date", by="permno", strategy="nearest")
                 .with_columns(pl.col(col).fill_null(pl.col(col + "_8k"))).drop("filing_date", col + "_8k"))
    return k


def _rep_contrib(weights, panel, filings) -> pl.DataFrame:
    """Total gross contribution (sum of w*ret) of each stock, labelled "TICKER, Company Name", sorted descending."""
    c = (weights.join(panel.select("permno", "eom", "ret_exc_lead1m"), on=["permno", "eom"], how="left")
         .with_columns(c=pl.col("weight") * pl.col("ret_exc_lead1m").fill_null(0.0))
         .group_by("permno").agg(contrib=pl.col("c").sum(), eom=pl.col("eom").max()))
    c = _rep_labels(c, panel, filings).with_columns(
        label=pl.col("ticker").fill_null("?") + ", " + pl.col("company_name").fill_null("?").str.to_titlecase())
    return c.sort("contrib", descending=True).select("permno", "label", "contrib")


def _rep_composition(weights, panel) -> dict:
    """Largest weight, top-10 share of gross, short-book market cap / dollar volume / small-cap share (monthly means)."""
    w = weights.to_pandas().assign(a=lambda x: x["weight"].abs())
    top10 = w.groupby("eom")["a"].apply(lambda s: s.nlargest(10).sum() / s.sum())
    me = "me_raw" if "me_raw" in panel.columns else "market_equity"
    dv = "dolvol_raw" if "dolvol_raw" in panel.columns else "dolvol_126d"
    s = (weights.filter(pl.col("weight") < 0).join(
        panel.select("permno", "eom", me, dv, "size_grp"), on=["permno", "eom"], how="left").to_pandas())
    s["a"] = -s["weight"]
    s["small"] = s["size_grp"].isin(["micro", "nano", "small"]) * s["a"]
    g = s.groupby("eom")
    wavg = lambda col: float(g.apply(lambda x: np.average(x[col].fillna(0), weights=x["a"])).mean())
    return {"largest_weight": float(w["a"].max()), "top10_share_of_gross": float(top10.mean()),
            "short_avg_market_cap": wavg(me), "short_median_market_cap": float(s[me].median()),
            "short_avg_dollar_volume": wavg(dv), "short_median_dollar_volume": float(s[dv].median()),
            "short_small_cap_share": float((g["small"].sum() / g["a"].sum()).mean()),
            "small_cap_groups": ["micro", "nano", "small"]}


def performance_pack(rets, weights, panel, filings, preds, cfg) -> dict:
    """Write output/performance.json and the charts in output/figures/. Returns the stats dict."""
    out = cfg["output_dir"]
    figs = out / "figures"
    stats = summary_stats(rets, cfg)
    p = preds if "ret_exc_lead1m" in preds.columns else preds.join(
        panel.select("permno", "eom", "ret_exc_lead1m"), on=["permno", "eom"], how="left")
    stats["oos_r2"] = oos_r2(p)
    stats["book"] = _rep_composition(weights, panel)
    stats["n_missing_returns"] = int(weights.join(panel.select("permno", "eom", "ret_exc_lead1m"), on=["permno", "eom"],
                                                  how="left")["ret_exc_lead1m"].is_null().sum())
    stats["notes"] = ["S&P 500 series is the total return index from SP500.csv", "returns are gross of trading costs"]
    d = rets.to_pandas().set_index("Date")
    title = lambda t: f"{t}, gross of trading costs, {d.index[0]:%b %Y} to {d.index[-1]:%b %Y}"
    cum = lambda s: (1 + s).cumprod() - 1
    dd = lambda s: (1 + s).cumprod() / (1 + s).cumprod().cummax() - 1
    anchor = lambda s: pd.concat([pd.Series([0.0], index=[d.index[0] - pd.offsets.MonthBegin(1)]), s])
    _rep_line({"Strategy": anchor(cum(d["total"])), "Benchmark": anchor(cum(d["benchmark"])), "S&P 500": anchor(cum(d["sp500"]))},
              title("Cumulative return"), figs / "cumulative_returns.png", ylabel="Cumulative return")
    _rep_line({"Strategy": anchor(dd(d["total"])), "S&P 500": anchor(dd(d["sp500"]))},
              title("Drawdown"), figs / "underwater.png", ylabel="Drawdown")
    _rep_line({"Active return (ann.)": d["active"].rolling(12).mean() * 12},
              title("Rolling 12-month annualized active return"), figs / "rolling_active_return.png", hline=0)
    _rep_line({"IR": np.sqrt(12) * d["active"].rolling(12).mean() / d["active"].rolling(12).std(ddof=1)},
              title("Rolling 12-month information ratio"), figs / "rolling_ir.png", hline=0)
    x = d["sp500"] - d["rf"]
    _rep_line({"Beta": d["excess"].rolling(12).cov(x) / x.rolling(12).var()},
              title("Rolling 12-month beta vs S&P 500"), figs / "rolling_beta.png", hline=0)
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(d["total"], bins=20, color="tab:blue", alpha=0.85)
    ax.axvline(d["benchmark"].mean(), color="red", linestyle="--", label="Avg monthly hurdle")
    ax.set_title(title("Distribution of monthly returns"))
    ax.legend()
    _rep_savefig(fig, figs / "return_histogram.png")
    c = _rep_contrib(weights, panel, filings).to_pandas()
    both = pd.concat([c.head(10), c.tail(10)])
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.barh(both["label"], both["contrib"], color=["tab:green" if v >= 0 else "tab:red" for v in both["contrib"]])
    ax.invert_yaxis()
    ax.set_title(title("Top/bottom return contributors (excess-return contribution)"))
    _rep_savefig(fig, figs / "contributors.png")
    stats["top_contributors"] = c.head(10).to_dict("records")
    stats["bottom_contributors"] = c.tail(10).to_dict("records")
    (out / "performance.json").write_text(json.dumps(stats, indent=2, default=float))
    return stats


def write_submission(weights, panel, filings, rets, cfg) -> dict:
    """output/holdings.csv (Date, PERMNO, TICKER, COMPANY NAME, WEIGHT in % of NAV) and output/returns.csv."""
    out = cfg["output_dir"]
    h = _rep_labels(weights.select("permno", "eom", "weight"), panel, filings)
    unl = h.filter(pl.col("ticker").is_null() | pl.col("company_name").is_null())["permno"].unique().to_list()
    h.sort("eom", "permno").select(
        Date=pl.col("eom").dt.offset_by("1mo").dt.month_start().dt.strftime("%Y-%m-%d"), PERMNO=pl.col("permno"),
        TICKER=pl.col("ticker").fill_null(""), **{"COMPANY NAME": pl.col("company_name").fill_null("")},
        WEIGHT=(pl.col("weight") * 100).round(6)).write_csv(out / "holdings.csv")
    rets.with_columns(Date=pl.col("Date").dt.strftime("%Y-%m-%d")).select(
        "Date", "total", "excess", "active", "long_leg", "short_leg", "benchmark", "sp500").write_csv(out / "returns.csv")
    if unl:
        print(f"WARNING: {len(unl)} stocks stay unlabeled after 8-K fill: {unl[:20]}")
    return {"unlabeled_permnos": unl}


# ===== src/pipeline.py =====
"""
src/pipeline.py - Orchestration of steps 1-14: caching, step-10 tuning, step-11 leakage tests, step-12 ablations.
main(cfg) is called by MAIN.py; one short function per step.
"""
import json
import time
from datetime import date, datetime
from pathlib import Path

import numpy as np
import polars as pl
import statsmodels.api as sm
from joblib import Parallel, delayed


_PIPE_T0 = time.time()
_PIPE_KEYS = ["permno", "eom"]
_PIPE_TONE = ["tone_mean", "tone_min", "tone_surprise"]


# ----------------------------------------------------------------------------- small helpers
def _pipe_log(msg):
    print(f"[{time.time() - _PIPE_T0:8.0f}s] {msg}", flush=True)


def _pipe_cached(path, fn):
    """Load parquet if present, else compute with fn() and write it."""
    path = Path(path)
    if path.exists():
        _pipe_log(f"cache hit {path.name}")
        return pl.read_parquet(path)
    out = fn()
    out.write_parquet(path)
    _pipe_log(f"cache written {path.name}")
    return out


def _pipe_cached_info(path, fn):
    """Like _pipe_cached, but fn() returns (frame, info) and info is kept in a sidecar JSON next to the parquet."""
    path = Path(path)
    side = path.with_suffix(".json")
    if path.exists():
        _pipe_log(f"cache hit {path.name}")
        return pl.read_parquet(path), (json.loads(side.read_text()) if side.exists() else None)
    out, info = fn()
    out.write_parquet(path)
    side.write_text(json.dumps(_pipe_clean(info), default=_pipe_jsonable))
    _pipe_log(f"cache written {path.name}")
    return out, info


def _pipe_path(cfg, name):
    """Cache path; smoke runs get their own files."""
    stem, ext = name.rsplit(".", 1)
    return Path(cfg["cache_dir"]) / f"{stem}{'_smoke' if cfg['smoke'] else ''}.{ext}"


def _pipe_jsonable(o):
    """json.dump default= hook: numpy / dates / paths / polars to plain Python."""
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return None if np.isnan(o) else float(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    if isinstance(o, (date, datetime)):
        return o.isoformat()
    if isinstance(o, Path):
        return str(o)
    if isinstance(o, pl.DataFrame):
        return o.to_dicts()
    return str(o)


def _pipe_clean(o):
    """Recursively replace NaN floats by None (JSON has no NaN) and tuple keys by strings."""
    if isinstance(o, dict):
        return {str(k): _pipe_clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_pipe_clean(v) for v in o]
    if isinstance(o, (float, np.floating)) and not np.isfinite(o):
        return None
    return o


def _pipe_dump(obj, name, cfg):
    path = Path(cfg["output_dir"]) / name
    path.write_text(json.dumps(_pipe_clean(obj), indent=2, default=_pipe_jsonable))
    _pipe_log(f"wrote {path.name}")


def _pipe_with_short(df, q, cfg):
    """Recompute short_eligible for a given short_me_q (mask may be an Expr or a Series)."""
    m = short_eligible_mask(df, q, cfg)
    return df.with_columns(m.alias("short_eligible"))


def _pipe_attach_target(preds, frame):
    """Add ret_exc_lead1m (needed by rank_ic / oos_r2) to a predictions frame."""
    return preds.drop("ret_exc_lead1m", strict=False).join(
        frame.select(_PIPE_KEYS + ["ret_exc_lead1m"]), on=_PIPE_KEYS, how="left")


def _pipe_scored(preds, frame, cfg):
    """Predictions + optimizer inputs (short_eligible, betas, sector, size_z = within-month z of log market cap, risk_factors columns)."""
    lm = pl.when(pl.col("me_raw") > 0).then(pl.col("me_raw").log())
    size_z = ((lm - lm.mean().over("eom")) / lm.std().over("eom")).fill_nan(None).fill_null(0.0).alias("size_z")
    cols = _PIPE_KEYS + ["short_eligible", "beta_kf", "beta_var", "sector", size_z] + [c for c in cfg["risk_factors"] if c not in ("sector",)]
    return preds.select(_PIPE_KEYS + ["score"]).join(frame.select(cols), on=_PIPE_KEYS, how="left")


def _pipe_ir(rets):
    a = rets["active"].to_numpy()
    sd = a.std(ddof=1) if len(a) > 1 else np.nan
    return float(np.sqrt(12) * a.mean() / sd) if sd and sd > 0 else float("nan")


def _pipe_beta(rets, cfg):
    """OLS of monthly excess return on S&P excess (sp500 - rf), Newey-West; returns {beta, t, alpha_m}."""
    rf = rets["benchmark"].to_numpy() - cfg["premium_annual"] / 12
    x = rets["sp500"].to_numpy() - rf
    y = rets["excess"].to_numpy()
    ok = np.isfinite(x) & np.isfinite(y)
    if ok.sum() < 5:
        return {"beta": float("nan"), "t": float("nan"), "alpha_m": float("nan")}
    r = sm.OLS(y[ok], sm.add_constant(x[ok])).fit(cov_type="HAC", cov_kwds={"maxlags": cfg["nw_lags"]})
    return {"beta": float(r.params[1]), "t": float(r.tvalues[1]), "alpha_m": float(r.params[0])}


def _pipe_ic(preds, frame, cfg):
    """Mean rank IC, ICIR (mean/std*sqrt12) and month count of a predictions frame."""
    ic = rank_ic(_pipe_attach_target(preds, frame), cfg)["ic"].drop_nulls().to_numpy()
    sd = ic.std(ddof=1) if len(ic) > 1 else np.nan
    return {"ic": float(ic.mean()) if len(ic) else float("nan"),
            "icir": float(ic.mean() / sd * np.sqrt(12)) if len(ic) > 1 and sd > 0 else float("nan"),
            "n_months": int(len(ic))}


# ----------------------------------------------------------------------------- steps 1-8 (data, features)
def _pipe_data(cfg):
    """Steps 1-3: raw panel, 147 factors, filings, preprocessed universe (cached) and missing-flag columns."""
    panel, factors, filings = load_inputs(cfg)
    _pipe_log(f"loaded panel {panel.shape}, filings {filings.shape}")

    def build():
        return preprocess(build_universe(panel, cfg), factors, cfg)[0]
    df = _pipe_cached(_pipe_path(cfg, "universe.parquet"), build)
    flag_cols = [c for c in df.columns if c.endswith("_miss")]
    return panel, factors, filings, df, flag_cols


def _pipe_kalman(panel, df, cfg, logs):
    """Step 8 on the RAW panel (all stocks), joined onto the universe."""
    def build():
        return kalman_betas(panel, cfg)
    kal, logs["kalman"] = _pipe_cached_info(_pipe_path(cfg, "kalman.parquet"), build)
    return df.drop(["beta_kf", "beta_var"], strict=False).join(kal, on=_PIPE_KEYS, how="left")


def _pipe_text(filings, panel, df, cfg):
    """Steps 6-7: event flags + FinBERT tone features; returns (frame with text cols, event cols)."""
    keys = df.select(_PIPE_KEYS)

    def build():
        ev = event_flags(filings, keys, cfg)
        tones = finbert_doc_tones(filings, df, cfg)
        return ev.join(tone_features(filings, tones, keys, cfg), on=_PIPE_KEYS, how="left")
    txt = _pipe_cached(_pipe_path(cfg, "text_features.parquet"), build)
    event_cols = [c for c in txt.columns if c not in _PIPE_KEYS + _PIPE_TONE]
    return df.join(txt, on=_PIPE_KEYS, how="left"), event_cols


def _pipe_gru(df, factors, cfg, logs):
    """Step 4 for each d in the grid; returns {d: embedding frame}."""
    embs = {}
    for d in cfg["gru_d_grid"]:
        def build(d=d):
            return gru_embeddings(df, factors, d, cfg)
        embs[d], info = _pipe_cached_info(_pipe_path(cfg, f"gru_d{d}.parquet"), build)
        logs.setdefault("gru", {})[d] = info
    return embs


def _pipe_frame(df, emb, q, cfg):
    """Full modelling frame for one GRU d and short_me_q."""
    return _pipe_with_short(df.join(emb, on=_PIPE_KEYS, how="left"), q, cfg)


# ----------------------------------------------------------------------------- step 10 tuning
def _pipe_book_job(scored, ltc, lb, lr, lf, rm, cfg):
    """Worker: one optimizer run over all months of `scored`."""
    return run_book(scored, ltc, lb, cfg, lam_risk=lr, lam_fac=lf, rm=rm)


def _pipe_tune(frames, feats, market, cfg, rm, vals=None):
    """Step 10: XGB on the 2021 window per d (skipped if `vals` given), then grid over
    (lam_tc, lam_beta, short_me_q, lam_risk, lam_fac) by validation IR. Validation months only. -> (choice, grid, rets, vals)"""
    win = windows(cfg)[0]
    fit, vals, tasks = vals is None, dict(vals or {}), []
    for d in cfg["gru_d_grid"]:
        fr = frames[d].filter(pl.col("target_month") <= win["test"][1])
        if fit:
            _, vals[d], info = fit_predict_year(fr, feats[d], win, cfg)
            _pipe_log(f"tune: d={d} xgb val IC {info.get('val_ic')}")
        for q in cfg["short_me_q_grid"]:
            sc = _pipe_scored(vals[d], _pipe_with_short(fr, q, cfg), cfg)
            tasks += [(d, ltc, lb, q, lr, lf, sc) for ltc in cfg["lambda_tc_grid"] for lb in cfg["lambda_beta_grid"]
                      for lr in cfg["lambda_risk_grid"] for lf in cfg["lambda_fac_grid"]]
    _pipe_log(f"tune: {len(tasks)} optimizer runs on {cfg['n_jobs']} workers")
    res = Parallel(n_jobs=cfg["n_jobs"], backend="loky")(
        delayed(_pipe_book_job)(sc, ltc, lb, lr, lf, rm, cfg) for d, ltc, lb, q, lr, lf, sc in tasks)
    grid, best = [], None
    for (d, ltc, lb, q, lr, lf, _), (w, log) in zip(tasks, res):
        rets, _ = book_returns(w, frames[d], market, cfg)
        ir = _pipe_ir(rets)
        grid.append({"d": d, "lam_tc": ltc, "lam_beta": lb, "short_me_q": q, "lam_risk": lr, "lam_fac": lf, "val_ir": ir,
                     "n_relaxed_months": sum(1 for r in log if (r.get("beta_tol") or 0) > cfg["beta_tol"] + 1e-12)})
        if np.isfinite(ir) and (best is None or ir > best[0]):
            best = (ir, grid[-1], rets)
    choice = {k: best[1][k] for k in ["d", "lam_tc", "lam_beta", "short_me_q", "lam_risk", "lam_fac"]} | {"val_ir": best[0]}
    return choice, grid, best[2], vals


def _pipe_beta_check(rets, cfg):
    """Chosen validation book vs S&P: beta is clearly nonzero (warning) when |t| > beta_check_t."""
    b = _pipe_beta(rets, cfg)
    b["warning"] = bool(abs(b["t"]) > cfg["beta_check_t"])
    if b["warning"]:
        print(f"WARNING: validation book beta to S&P = {b['beta']:.3f} (t={b['t']:.2f}) is clearly nonzero", flush=True)
    return b


def _pipe_beta_variant(name, df, panel, cfg, logs):
    """Beta estimates [permno, eom, beta_kf, beta_var] for one variant (kf_rfloor is cached)."""
    kf = df.select(_PIPE_KEYS + ["beta_kf", "beta_var"])
    if name == "kf":
        return kf
    if name == "kf_rfloor":
        def build():
            return kalman_betas(panel, cfg, r_floor=cfg["kalman_r_floor"])
        out, logs["kalman_rfloor"] = _pipe_cached_info(_pipe_path(cfg, "kalman_rfloor.parquet"), build)
        return df.select(_PIPE_KEYS).join(out, on=_PIPE_KEYS, how="left")
    k, b = cfg["beta_shrink"], pl.col("beta_60m")          # b60_shrunk; raw beta_60m clipped at its 1st/99th pct (raw reaches +/-1e4)
    fit = panel.filter(pl.col("eom") <= date.fromisoformat(cfg["kalman_fit_end_eom"]))["beta_60m"]   # pre-2019 only
    lo, hi = fit.quantile(0.01), fit.quantile(0.99)
    raw = panel.select(_PIPE_KEYS + [b.clip(lo, hi).alias("beta_60m")])
    return kf.join(raw, on=_PIPE_KEYS, how="left").with_columns(
        beta_kf=pl.when(b.is_not_null()).then((1 - k) * b + k).otherwise(pl.col("beta_kf"))).drop("beta_60m")


def _pipe_swap_beta(frames, bv):
    return {d: fr.drop(["beta_kf", "beta_var"]).join(bv, on=_PIPE_KEYS, how="left") for d, fr in frames.items()}


def _pipe_beta_fix(df, panel, frames, feats, vals, choice, chk, market, cfg, rm, logs):
    """Step 10 beta fix: validation beta of each variant at the current choice; if the best is not "kf", redo the grid.
    -> (frames, choice, grid, check, log); grid is None when "kf" is kept."""
    fix, swapped = {"variants": {}, "choice_kf": choice, "check_kf": chk}, {}
    for name in cfg["beta_variants"]:
        swapped[name] = _pipe_swap_beta(frames, _pipe_beta_variant(name, df, panel, cfg, logs))
        fr = _pipe_with_short(swapped[name][choice["d"]], choice["short_me_q"], cfg)
        v = fix["variants"][name] = _pipe_beta(_pipe_run_book_stats(vals[choice["d"]], fr, choice, market, cfg, rm)[1], cfg)
        _pipe_log(f"beta fix: {name} val beta {v['beta']:.3f} (t={v['t']:.2f})")
    best = min(fix["variants"], key=lambda n: abs(fix["variants"][n]["beta"]) if np.isfinite(fix["variants"][n]["beta"]) else np.inf)
    fix["chosen"], grid = best, None
    if best != "kf":
        frames = swapped[best]
        choice, grid, rets, _ = _pipe_tune(frames, feats, market, cfg, rm, vals)
        chk = _pipe_beta_check(rets, cfg)
        fix |= {"choice_final": choice, "check_final": chk}
    _pipe_log(f"beta fix: variant {best}; val beta {chk['beta']:.3f} (t={chk['t']:.2f}); choice {choice}")
    return frames, choice, grid, chk, fix


# ----------------------------------------------------------------------------- full run + step 11 / 12 helpers
def _pipe_run_book_stats(preds, frame, choice, market, cfg, rm):
    """Book with chosen lambdas on test predictions -> (weights, rets, IR, beta)."""
    w, _ = run_book(_pipe_scored(preds, frame, cfg), choice["lam_tc"], choice["lam_beta"], cfg, lam_risk=choice["lam_risk"],
                    lam_fac=choice["lam_fac"], rm=rm)
    rets, n_miss = book_returns(w, frame, market, cfg)
    return w, rets, n_miss


def _pipe_leak_filings(filings, feats):
    """Number of stock-months flagged has_filing=1 without a filing in that calendar month, and filings used after their eom."""
    f = filings.select("permno", pl.col("filing_date").dt.month_end().alias("eom"), "filing_date")
    have = f.group_by(_PIPE_KEYS).agg(pl.col("filing_date").max().alias("last"))
    x = feats.filter(pl.col("has_filing") == 1).select(_PIPE_KEYS).join(have, on=_PIPE_KEYS, how="left")
    return {"flagged_without_filing": int(x["last"].is_null().sum()),
            "filing_after_eom": int((x["last"] > x["eom"]).sum())}


def _pipe_leak_windows(wins):
    """Violations of train < val < test ordering by target month, and of 'train ends before test year'."""
    bad = 0
    for w in wins:
        bad += not (w["train"][1] < w["val"][0] <= w["val"][1] < w["test"][0])
        bad += w["train"][1].year >= w["year"] or w["val"][1].year >= w["year"]
        bad += w["test"][0].year != w["year"]
    return int(bad)


def _pipe_leak_target(df, features, target="ret_exc_lead1m"):
    """Feature columns that are the target (by name) or numerically identical / perfectly correlated with it."""
    bad = [c for c in features if c == target or "lead" in c]
    num = [c for c in features if c not in bad and df.schema[c].is_numeric()]
    if num:
        cors = df.select([pl.corr(pl.col(c).cast(pl.Float64), pl.col(target)).alias(c) for c in num]).row(0)
        bad += [c for c, r in zip(num, cors) if r is not None and abs(r) > 0.999]
    return bad


def _pipe_leak_target_months(infos):
    """Windows whose fitted train/val rows reach a target month >= Y-01-01 (taken from the actual fits)."""
    return [{"year": i["year"], "max_target_month": i["train_max_target"]}
            for i in infos if i["train_max_target"] >= date(i["year"], 1, 1)]


def _pipe_leak_dups(df):
    return int(df.height - df.unique(subset=_PIPE_KEYS).height)


def _pipe_leakage(frame, filings, feats, event_cols, preds_shuf, choice, market, cfg, rm, infos):
    """Step 11: structural checks plus shuffled-label run (test IC and IR should be ~0)."""
    ev = frame.filter(pl.col("has_filing") == 1) if "has_filing" in frame.columns else frame.head(0)
    out = {"filings": _pipe_leak_filings(filings, ev) if ev.height else {"flagged_without_filing": 0, "filing_after_eom": 0},
           "window_violations": _pipe_leak_windows(windows(cfg)),
           "target_like_features": _pipe_leak_target(frame, feats),
           "duplicate_permno_eom": _pipe_leak_dups(frame),
           "train_target_month_violations": _pipe_leak_target_months(infos),
           "shuffled_ic": _pipe_ic(preds_shuf, frame, cfg)}
    _, rets, _ = _pipe_run_book_stats(preds_shuf, frame, choice, market, cfg, rm)
    out["shuffled_ir"] = _pipe_ir(rets)
    out["shuffled_beta"] = _pipe_beta(rets, cfg)
    out["passed_structural"] = (out["filings"]["flagged_without_filing"] == 0 and out["filings"]["filing_after_eom"] == 0
                                and out["window_violations"] == 0 and not out["target_like_features"]
                                and out["duplicate_permno_eom"] == 0 and not out["train_target_month_violations"])
    out["ic_close_to_zero"] = bool(abs(out["shuffled_ic"]["ic"]) < 0.01)
    out["ir_close_to_zero"] = bool(abs(out["shuffled_ir"]) < 1.0)
    if not (out["ic_close_to_zero"] and out["ir_close_to_zero"]):
        print(f"WARNING: shuffled-label run not ~0: IC {out['shuffled_ic']['ic']:.4f}, IR {out['shuffled_ir']:.2f}", flush=True)
    return out


def _pipe_ablations(frame, runs, choice, market, cfg, rm):
    """Step 12: per ablation - validation/test rank IC, ICIR, IR, beta (chosen lambdas); IC on has_filing=1 rows for 4 and 5."""
    jobs = [r[k] for r in runs.values() for k in ("preds", "val")]
    books = Parallel(n_jobs=min(cfg["n_jobs"], len(jobs)), backend="loky")(
        delayed(_pipe_run_book_stats)(p, frame, choice, market, cfg, rm) for p in jobs)
    out = {"features_note": "ablation 1 = 147 factors (ridge), 2 = the 147 factors only (XGB); missing-value flags enter from "
                            "ablation 3 onward; 5 = full main feature set. val_ir/val_beta: book on 2021-window val_pred."}
    for i, (name, r) in enumerate(runs.items()):
        _, rets, n_miss = books[2 * i]
        vrets = books[2 * i + 1][1]
        o = {"features": r["n_features"], "val_ir": _pipe_ir(vrets), "val_beta": _pipe_beta(vrets, cfg)["beta"], "test": _pipe_ic(r["preds"], frame, cfg), "val_2021": _pipe_ic(r["val"], frame, cfg),
             "val_ic_by_year": [i.get("val_ic") for i in r["infos"]],
             "ir": _pipe_ir(rets), "beta": _pipe_beta(rets, cfg), "n_missing_returns": n_miss}
        if r.get("has_filing_ic"):
            hf = frame.filter(pl.col("has_filing") == 1).select(_PIPE_KEYS)
            o["test_has_filing_rows"] = _pipe_ic(r["preds"].join(hf, on=_PIPE_KEYS, how="inner"), frame, cfg)
        out[name] = o
    return out


# ----------------------------------------------------------------------------- main
def main(cfg):
    """Run steps 1-14 end to end."""
    logs, out_dir = {}, Path(cfg["output_dir"])
    panel, factors, filings, df, flag_cols = _pipe_data(cfg)
    df = _pipe_kalman(panel, df, cfg, logs)
    df, event_cols = _pipe_text(filings, panel, df, cfg)
    embs = _pipe_gru(df, factors, cfg, logs)
    market = load_market(cfg)

    base = factors + flag_cols
    gru_cols = lambda d: [f"gru_{i}" for i in range(1, d + 1)]
    feats = {d: base + gru_cols(d) + event_cols + _PIPE_TONE for d in cfg["gru_d_grid"]}
    frames = {d: _pipe_frame(df, embs[d], cfg["short_me_q"], cfg) for d in cfg["gru_d_grid"]}
    t0 = time.time()
    rm = risk_model(frames[cfg["gru_d_grid"][0]], cfg)     # once per run: independent of d, betas, short_me_q
    _pipe_log(f"risk model: {len(rm['L'])} months with a covariance, {time.time() - t0:.1f}s")

    # step 10: tuning on 2019-2020 validation
    choice, grid, val_rets, vals = _pipe_tune(frames, feats, market, cfg, rm)
    beta_chk, beta_fix = _pipe_beta_check(val_rets, cfg), None
    if beta_chk["warning"]:
        frames, choice, grid2, beta_chk, beta_fix = _pipe_beta_fix(df, panel, frames, feats, vals, choice, beta_chk, market, cfg, rm, logs)
        if grid2:
            beta_fix["grid_kf"], grid = grid, grid2
    _pipe_log(f"step 10 choice {choice}; validation beta {beta_chk}")
    d = choice["d"]
    frame = _pipe_with_short(frames[d], choice["short_me_q"], cfg)
    full = feats[d]
    _pipe_dump({"choice": choice, "beta_check": beta_chk, "beta_fix": beta_fix, "grid": grid, "logs": logs}, "settings_log.json", cfg)

    # step 5 + 9: full schedule, predictions, book, performance, submission
    preds, val_2021, infos = run_schedule(frame, full, cfg)
    preds = preds.select(_PIPE_KEYS + ["score", "ret_hat"])
    preds.write_parquet(out_dir / "predictions.parquet")
    weights, rets, n_miss = _pipe_run_book_stats(preds, frame, choice, market, cfg, rm)
    _pipe_log(f"full book: IR {_pipe_ir(rets):.3f}, missing returns {n_miss}")
    performance_pack(rets, weights, frame, filings, _pipe_attach_target(preds, frame), cfg)
    write_submission(weights, frame, filings, rets, cfg)
    _pipe_dump({"choice": choice, "beta_check": beta_chk, "beta_fix": beta_fix, "grid": grid, "logs": logs, "xgb_infos": infos,
                "test_ic": _pipe_ic(preds, frame, cfg), "test_ir": _pipe_ir(rets), "test_beta": _pipe_beta(rets, cfg)},
               "settings_log.json", cfg)

    # step 12: ablations (each run reuses the chosen lambdas / short_me_q / d)
    sets = {"1_ridge_147": (factors, "ridge", False),
            "2_xgb_base": (factors, "xgb", False),
            "3_plus_gru": (base + gru_cols(d), "xgb", False),
            "4_plus_event": (base + gru_cols(d) + event_cols, "xgb", True)}
    runs = {}
    for name, (cols, model, hf) in sets.items():
        p, v, i = run_schedule(frame, cols, cfg, model=model)
        runs[name] = {"preds": p, "val": v, "infos": i, "n_features": len(cols), "has_filing_ic": hf}
        _pipe_log(f"ablation {name} done")
    runs["5_plus_tone"] = {"preds": preds, "val": val_2021, "infos": infos, "n_features": len(full), "has_filing_ic": True}
    _pipe_dump(_pipe_ablations(frame, runs, choice, market, cfg, rm), "ablations.json", cfg)

    # step 11: leakage tests incl. shuffled-label run
    shuf, _, _ = run_schedule(frame, full, cfg, shuffle=True)
    leak = _pipe_leakage(frame, filings, full, event_cols, shuf, choice, market, cfg, rm, infos)
    _pipe_dump(leak, "leakage_tests.json", cfg)
    assert leak["filings"]["flagged_without_filing"] == 0 and leak["filings"]["filing_after_eom"] == 0,         f"leakage: filing_date after eom / flagged without filing: {leak['filings']}"
    assert leak["window_violations"] == 0, "leakage: train < val < test window ordering violated"
    assert not leak["train_target_month_violations"], f"leakage: training target months reach test year: {leak['train_target_month_violations']}"
    assert not leak["target_like_features"], f"leakage: target-identical features: {leak['target_like_features']}"
    assert leak["duplicate_permno_eom"] == 0, "leakage: duplicate (permno, eom) keys"
    _pipe_log("pipeline complete")


if __name__ == "__main__":
    main(CONFIG)
